### ISSUE TITLE
Please move it under the appropriate menu

### ISSUE THREAD

**Issue by pcav** [jeremyk6/qgeric#2]
Presumably Vector

**Comment by jeremyk6** [comment]
I wasn't sure where to put the menu but vector seems appropriate, thanks :)  .
Fixed in https://github.com/jeremyk6/qgeric/commit/217220399f6e06dec1c48fe3e0e152b18e878f9e .

**Comment by pcav** [comment]
Please let me know when you upload a new fixed version.
Thanks.

**Comment by jeremyk6** [comment]
I just uploaded a fixed version.
