### ISSUE TITLE
every selected feature saved six times after saving in a memorylayer

### ISSUE THREAD

**Issue by jodeutmann** [jeremyk6/qgeric#4]
Hello,
first, thank you for this great plugin! Very useful.

I select some points with the circle selection. In the result tab, the number of features are displayed as 315. 

![image](https://user-images.githubusercontent.com/8985259/28123947-91337ae4-6722-11e7-9c83-cb8e21b2e164.png)

After saving the selected points with your plugin in a memorylayer, the number of saved features is displayed as 1890. 

![image](https://user-images.githubusercontent.com/8985259/28124160-2b23afca-6723-11e7-9d9e-48aac7309907.png)

Every object is saved six times instead of one.

Best regards
Joachim Deutmann

**Comment by jeremyk6** [comment]
Fixed in https://github.com/jeremyk6/qgeric/commit/096b2850754beda4bf63a98f2c0baf5786e188fc .
Sorry for the (very long) delay. I don't work much on this project as QGis is not part of my job anymore :( .
